// Generated by SwiftProto Schema Compiler (C++). Do not edit.
#pragma once
#include "encoder.h"
#include "decoder.h"
#include "json.hpp"
#include <vector>
#include <string_view>
#include <cstdint>

struct Address {
  std::string_view city;

  void serialize(std::vector<uint8_t> &buf) const {
    if (!city.empty()) write_string(1, city, buf);
  }

  void deserialize(const std::vector<uint8_t> &buf, size_t &pos, size_t limit) {
    while (pos < limit) {
      Tag tag = read_tag(buf, pos);
      switch (tag.field_number) {
        case 1:
          if (tag.wire_type == LENGTH_DELIMITED) city = read_string_view(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        default:
          skip_field(buf, pos, tag.wire_type);
          break;
      }
    }
  }
};

struct Merchant {
  int64_t id = 0;
  std::string_view name;
  float fraud_rate = 0.0f;
  bool active = false;
  int64_t balance = 0;
  Address address;
  std::vector<int64_t> tags;
  std::vector<std::string_view> products;

  void serialize(std::vector<uint8_t> &buf) const {
    if (id != 0) write_int64(1, id, buf);
    if (!name.empty()) write_string(2, name, buf);
    if (fraud_rate != 0.0f) write_float(3, fraud_rate, buf);
    if (active) write_bool(4, active, buf);
    if (balance != 0) write_int64(5, balance, buf);
    {
      std::vector<uint8_t> temp_buf;
      address.serialize(temp_buf);
      if (!temp_buf.empty()) {
        write_tag(6, LENGTH_DELIMITED, buf);
        encode_varint(temp_buf.size(), buf);
        buf.insert(buf.end(), temp_buf.begin(), temp_buf.end());
      }
    }
    for (auto val : tags) write_int64(7, val, buf);
    for (auto val : products) write_string(8, val, buf);
  }

  void deserialize(const std::vector<uint8_t> &buf, size_t &pos, size_t limit) {
    while (pos < limit) {
      Tag tag = read_tag(buf, pos);
      switch (tag.field_number) {
        case 1:
          if (tag.wire_type == VARINT) id = read_int64(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 2:
          if (tag.wire_type == LENGTH_DELIMITED) name = read_string_view(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 3:
          if (tag.wire_type == FIXED32) fraud_rate = read_float(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 4:
          if (tag.wire_type == VARINT) active = read_bool(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 5:
          if (tag.wire_type == VARINT) balance = read_int64(buf, pos);
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 6:
          if (tag.wire_type == LENGTH_DELIMITED) {
            uint64_t len = decode_varint(buf, pos);
            size_t sub_limit = pos + len;
            address.deserialize(buf, pos, sub_limit);
          }
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 7:
          if (tag.wire_type == VARINT) tags.push_back(read_int64(buf, pos));
          else skip_field(buf, pos, tag.wire_type);
          break;
        case 8:
          if (tag.wire_type == LENGTH_DELIMITED) products.push_back(read_string_view(buf, pos));
          else skip_field(buf, pos, tag.wire_type);
          break;
        default:
          skip_field(buf, pos, tag.wire_type);
          break;
      }
    }
  }
};

inline void to_json(nlohmann::json &j, const Address &msg) {
  j = nlohmann::json{
    {"city", std::string(msg.city)}
  };
}

inline void from_json(const nlohmann::json &j, Address &msg) {
  if (j.contains("city")) {
    msg.city = j.at("city").get_ref<const std::string&>();
  }
}

inline void to_json(nlohmann::json &j, const Merchant &msg) {
  j = nlohmann::json{
    {"id", msg.id},
    {"name", std::string(msg.name)},
    {"fraud_rate", msg.fraud_rate},
    {"active", msg.active},
    {"balance", msg.balance},
    {"address", msg.address},
    {"tags", msg.tags},
    {"products", [&msg]() {
      std::vector<std::string> v;
      for (auto sv : msg.products) v.push_back(std::string(sv));
      return v;
    }()}
  };
}

inline void from_json(const nlohmann::json &j, Merchant &msg) {
  if (j.contains("id")) {
    j.at("id").get_to(msg.id);
  }
  if (j.contains("name")) {
    msg.name = j.at("name").get_ref<const std::string&>();
  }
  if (j.contains("fraud_rate")) {
    j.at("fraud_rate").get_to(msg.fraud_rate);
  }
  if (j.contains("active")) {
    j.at("active").get_to(msg.active);
  }
  if (j.contains("balance")) {
    j.at("balance").get_to(msg.balance);
  }
  if (j.contains("address")) {
    j.at("address").get_to(msg.address);
  }
  if (j.contains("tags")) {
    j.at("tags").get_to(msg.tags);
  }
  if (j.contains("products")) {
    if (j.at("products").is_array()) {
      msg.products.clear();
      for (const auto &item : j.at("products")) {
        msg.products.push_back(item.get_ref<const std::string&>());
      }
    }
  }
}

