#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <unordered_set>
#include <algorithm>
#include <cctype>
#include <stdexcept>

// Helper to strip single-line and block comments from the proto content
std::string strip_comments(const std::string &content) {
  std::string result;
  size_t i = 0;
  while (i < content.size()) {
    if (i + 1 < content.size() && content[i] == '/' && content[i+1] == '/') {
      i += 2;
      while (i < content.size() && content[i] != '\n') {
        i++;
      }
    } else if (i + 1 < content.size() && content[i] == '/' && content[i+1] == '*') {
      i += 2;
      while (i + 1 < content.size() && !(content[i] == '*' && content[i+1] == '/')) {
        i++;
      }
      i += 2;
    } else {
      result.push_back(content[i++]);
    }
  }
  return result;
}

// Simple tokenizer that splits by spaces and keeps special chars { } = ;
std::vector<std::string> tokenize(const std::string &content) {
  std::vector<std::string> tokens;
  std::string current;
  for (size_t i = 0; i < content.size(); ++i) {
    char c = content[i];
    if (std::isspace(c)) {
      if (!current.empty()) {
        tokens.push_back(current);
        current.clear();
      }
    } else if (c == '{' || c == '}' || c == '=' || c == ';') {
      if (!current.empty()) {
        tokens.push_back(current);
        current.clear();
      }
      tokens.push_back(std::string(1, c));
    } else {
      current.push_back(c);
    }
  }
  if (!current.empty()) {
    tokens.push_back(current);
  }
  return tokens;
}

struct Field {
  bool is_repeated;
  std::string proto_type;
  std::string name;
  int tag;

  std::string get_cpp_type(const std::unordered_set<std::string> &known_messages) const {
    std::string base;
    if (proto_type == "int64") base = "int64_t";
    else if (proto_type == "bool") base = "bool";
    else if (proto_type == "float") base = "float";
    else if (proto_type == "string") base = "std::string_view";
    else if (known_messages.count(proto_type)) base = proto_type;
    else throw std::runtime_error("Unknown type: " + proto_type);

    if (is_repeated) return "std::vector<" + base + ">";
    return base;
  }

  std::string get_default_initializer(const std::unordered_set<std::string> &known_messages) const {
    if (is_repeated) return "";
    if (proto_type == "int64") return " = 0";
    if (proto_type == "bool") return " = false";
    if (proto_type == "float") return " = 0.0f";
    return "";
  }
};

struct Message {
  std::string name;
  std::vector<Field> fields;
};

std::vector<Message> parse_messages(const std::vector<std::string> &tokens) {
  std::vector<Message> messages;
  size_t i = 0;
  while (i < tokens.size()) {
    if (tokens[i] == "message") {
      i++;
      if (i >= tokens.size()) break;
      Message msg;
      msg.name = tokens[i++];
      if (i < tokens.size() && tokens[i] == "{") {
        i++;
        while (i < tokens.size() && tokens[i] != "}") {
          bool is_repeated = false;
          if (tokens[i] == "repeated") {
            is_repeated = true;
            i++;
          }
          if (i >= tokens.size()) break;
          std::string type = tokens[i++];
          if (i >= tokens.size()) break;
          std::string name = tokens[i++];
          if (i >= tokens.size()) break;
          if (tokens[i] == "=") {
            i++;
            if (i >= tokens.size()) break;
            int tag = std::stoi(tokens[i++]);
            if (i < tokens.size() && tokens[i] == ";") {
              i++;
            }
            msg.fields.push_back({is_repeated, type, name, tag});
          }
        }
        if (i < tokens.size() && tokens[i] == "}") {
          i++;
        }
        messages.push_back(msg);
      }
    } else {
      i++;
    }
  }
  return messages;
}

std::string generate_cpp(const std::vector<Message> &messages) {
  std::unordered_set<std::string> known_messages;
  for (const auto &m : messages) {
    known_messages.insert(m.name);
  }

  std::string out = "// Generated by SwiftProto Schema Compiler (C++). Do not edit.\n";
  out += "#pragma once\n";
  out += "#include \"encoder.h\"\n";
  out += "#include \"decoder.h\"\n";
  out += "#include \"json.hpp\"\n";
  out += "#include <vector>\n";
  out += "#include <string_view>\n";
  out += "#include <cstdint>\n\n";

  // 1. Generate Struct definitions
  for (const auto &msg : messages) {
    out += "struct " + msg.name + " {\n";
    for (const auto &f : msg.fields) {
      std::string cpp_type = f.get_cpp_type(known_messages);
      std::string init = f.get_default_initializer(known_messages);
      out += "  " + cpp_type + " " + f.name + init + ";\n";
    }
    out += "\n  void serialize(std::vector<uint8_t> &buf) const {\n";
    for (const auto &f : msg.fields) {
      if (f.is_repeated) {
        if (f.proto_type == "int64") {
          out += "    for (auto val : " + f.name + ") write_int64(" + std::to_string(f.tag) + ", val, buf);\n";
        } else if (f.proto_type == "bool") {
          out += "    for (auto val : " + f.name + ") write_bool(" + std::to_string(f.tag) + ", val, buf);\n";
        } else if (f.proto_type == "float") {
          out += "    for (auto val : " + f.name + ") write_float(" + std::to_string(f.tag) + ", val, buf);\n";
        } else if (f.proto_type == "string") {
          out += "    for (auto val : " + f.name + ") write_string(" + std::to_string(f.tag) + ", val, buf);\n";
        } else if (known_messages.count(f.proto_type)) {
          out += "    for (const auto &val : " + f.name + ") {\n";
          out += "      std::vector<uint8_t> temp_buf;\n";
          out += "      val.serialize(temp_buf);\n";
          out += "      write_tag(" + std::to_string(f.tag) + ", LENGTH_DELIMITED, buf);\n";
          out += "      encode_varint(temp_buf.size(), buf);\n";
          out += "      buf.insert(buf.end(), temp_buf.begin(), temp_buf.end());\n";
          out += "    }\n";
        }
      } else {
        if (f.proto_type == "int64") {
          out += "    if (" + f.name + " != 0) write_int64(" + std::to_string(f.tag) + ", " + f.name + ", buf);\n";
        } else if (f.proto_type == "bool") {
          out += "    if (" + f.name + ") write_bool(" + std::to_string(f.tag) + ", " + f.name + ", buf);\n";
        } else if (f.proto_type == "float") {
          out += "    if (" + f.name + " != 0.0f) write_float(" + std::to_string(f.tag) + ", " + f.name + ", buf);\n";
        } else if (f.proto_type == "string") {
          out += "    if (!" + f.name + ".empty()) write_string(" + std::to_string(f.tag) + ", " + f.name + ", buf);\n";
        } else if (known_messages.count(f.proto_type)) {
          out += "    {\n";
          out += "      std::vector<uint8_t> temp_buf;\n";
          out += "      " + f.name + ".serialize(temp_buf);\n";
          out += "      if (!temp_buf.empty()) {\n";
          out += "        write_tag(" + std::to_string(f.tag) + ", LENGTH_DELIMITED, buf);\n";
          out += "        encode_varint(temp_buf.size(), buf);\n";
          out += "        buf.insert(buf.end(), temp_buf.begin(), temp_buf.end());\n";
          out += "      }\n";
          out += "    }\n";
        }
      }
    }
    out += "  }\n\n";

    out += "  void deserialize(const std::vector<uint8_t> &buf, size_t &pos, size_t limit) {\n";
    out += "    while (pos < limit) {\n";
    out += "      Tag tag = read_tag(buf, pos);\n";
    out += "      switch (tag.field_number) {\n";
    for (const auto &f : msg.fields) {
      out += "        case " + std::to_string(f.tag) + ":\n";
      if (f.is_repeated) {
        if (f.proto_type == "int64") {
          out += "          if (tag.wire_type == VARINT) " + f.name + ".push_back(read_int64(buf, pos));\n";
        } else if (f.proto_type == "bool") {
          out += "          if (tag.wire_type == VARINT) " + f.name + ".push_back(read_bool(buf, pos));\n";
        } else if (f.proto_type == "float") {
          out += "          if (tag.wire_type == FIXED32) " + f.name + ".push_back(read_float(buf, pos));\n";
        } else if (f.proto_type == "string") {
          out += "          if (tag.wire_type == LENGTH_DELIMITED) " + f.name + ".push_back(read_string_view(buf, pos));\n";
        } else if (known_messages.count(f.proto_type)) {
          out += "          if (tag.wire_type == LENGTH_DELIMITED) {\n";
          out += "            uint64_t len = decode_varint(buf, pos);\n";
          out += "            size_t sub_limit = pos + len;\n";
          out += "            " + f.proto_type + " sub_msg;\n";
          out += "            sub_msg.deserialize(buf, pos, sub_limit);\n";
          out += "            " + f.name + ".push_back(sub_msg);\n";
          out += "          }\n";
        }
      } else {
        if (f.proto_type == "int64") {
          out += "          if (tag.wire_type == VARINT) " + f.name + " = read_int64(buf, pos);\n";
        } else if (f.proto_type == "bool") {
          out += "          if (tag.wire_type == VARINT) " + f.name + " = read_bool(buf, pos);\n";
        } else if (f.proto_type == "float") {
          out += "          if (tag.wire_type == FIXED32) " + f.name + " = read_float(buf, pos);\n";
        } else if (f.proto_type == "string") {
          out += "          if (tag.wire_type == LENGTH_DELIMITED) " + f.name + " = read_string_view(buf, pos);\n";
        } else if (known_messages.count(f.proto_type)) {
          out += "          if (tag.wire_type == LENGTH_DELIMITED) {\n";
          out += "            uint64_t len = decode_varint(buf, pos);\n";
          out += "            size_t sub_limit = pos + len;\n";
          out += "            " + f.name + ".deserialize(buf, pos, sub_limit);\n";
          out += "          }\n";
        }
      }
      out += "          else skip_field(buf, pos, tag.wire_type);\n";
      out += "          break;\n";
    }
    out += "        default:\n";
    out += "          skip_field(buf, pos, tag.wire_type);\n";
    out += "          break;\n";
    out += "      }\n";
    out += "    }\n";
    out += "  }\n";
    out += "};\n\n";
  }

  // 2. Generate JSON support helpers (to_json and from_json)
  for (const auto &msg : messages) {
    // to_json
    out += "inline void to_json(nlohmann::json &j, const " + msg.name + " &msg) {\n";
    out += "  j = nlohmann::json{\n";
    for (size_t fi = 0; fi < msg.fields.size(); ++fi) {
      const auto &f = msg.fields[fi];
      out += "    {\"" + f.name + "\", ";
      if (f.is_repeated) {
        if (f.proto_type == "string") {
          out += "[&msg]() {\n";
          out += "      std::vector<std::string> v;\n";
          out += "      for (auto sv : msg." + f.name + ") v.push_back(std::string(sv));\n";
          out += "      return v;\n";
          out += "    }()";
        } else {
          out += "msg." + f.name;
        }
      } else {
        if (f.proto_type == "string") {
          out += "std::string(msg." + f.name + ")";
        } else {
          out += "msg." + f.name;
        }
      }
      out += "}";
      if (fi < msg.fields.size() - 1) out += ",\n";
    }
    out += "\n  };\n";
    out += "}\n\n";

    // from_json
    out += "inline void from_json(const nlohmann::json &j, " + msg.name + " &msg) {\n";
    for (const auto &f : msg.fields) {
      out += "  if (j.contains(\"" + f.name + "\")) {\n";
      if (f.is_repeated) {
        if (f.proto_type == "string") {
          out += "    if (j.at(\"" + f.name + "\").is_array()) {\n";
          out += "      msg." + f.name + ".clear();\n";
          out += "      for (const auto &item : j.at(\"" + f.name + "\")) {\n";
          out += "        msg." + f.name + ".push_back(item.get_ref<const std::string&>());\n";
          out += "      }\n";
          out += "    }\n";
        } else {
          out += "    j.at(\"" + f.name + "\").get_to(msg." + f.name + ");\n";
        }
      } else {
        if (f.proto_type == "string") {
          out += "    msg." + f.name + " = j.at(\"" + f.name + "\").get_ref<const std::string&>();\n";
        } else {
          out += "    j.at(\"" + f.name + "\").get_to(msg." + f.name + ");\n";
        }
      }
      out += "  }\n";
    }
    out += "}\n\n";
  }

  return out;
}

int main(int argc, char *argv[]) {
  if (argc < 3) {
    std::cerr << "Usage: " << argv[0] << " <schema_file.proto> <output_header.h>\n";
    return 1;
  }

  std::string schema_path = argv[1];
  std::string output_path = argv[2];

  std::ifstream schema_file(schema_path);
  if (!schema_file.is_open()) {
    std::cerr << "Failed to open schema file: " << schema_path << "\n";
    return 1;
  }

  std::string content((std::istreambuf_iterator<char>(schema_file)),
                       std::istreambuf_iterator<char>());
  schema_file.close();

  try {
    std::string stripped = strip_comments(content);
    auto tokens = tokenize(stripped);
    auto messages = parse_messages(tokens);
    std::string cpp_code = generate_cpp(messages);

    std::ofstream output_file(output_path);
    if (!output_file.is_open()) {
      std::cerr << "Failed to open output file: " << output_path << "\n";
      return 1;
    }
    output_file << cpp_code;
    output_file.close();

    std::cout << "Successfully generated " << output_path << " from " << schema_path << "\n";
  } catch (const std::exception &e) {
    std::cerr << "Compilation error: " << e.what() << "\n";
    return 1;
  }

  return 0;
}
